version: '3.8'

services:
  # Next.js Development Server
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/auth/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/auth/sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard/bookmarks
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard/bookmarks
      - NEXT_PUBLIC_SENTRY_DISABLED=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - bookmark-network-dev
    restart: unless-stopped

  # MongoDB for Development
  mongodb-dev:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=bookmarks
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - bookmark-network-dev
    restart: unless-stopped

  # MongoDB Admin Interface for Development
  mongo-express-dev:
    image: mongo-express:1.0.0
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongodb-dev:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb-dev
    networks:
      - bookmark-network-dev
    restart: unless-stopped

volumes:
  mongodb_dev_data:
    driver: local

networks:
  bookmark-network-dev:
    driver: bridge